import type { Question } from "@/lib/types";

/**
 * DB 設計トラック (db-001 〜 db-018)
 * 正規化 / 主キー外部キー設計 / リレーションパターン / インデックス /
 * マイグレーション運用 / アンチパターン
 */
export const dbQuestions: Question[] = [
  // ===========================================================================
  // 🗂️ DB 設計 基礎 (db-001 〜 db-018)
  // ===========================================================================
  {
    id: "db-001",
    categoryId: "db-design",
    difficulty: "beginner",
    type: "choice",
    question: "第 1 正規形 (1NF) の条件として正しいのは？",
    choices: [
      "BCNF を満たす",
      "1 つのセルには 1 つの値だけ (配列・JSON で複数値を持たない)",
      "全カラムが PK を参照する",
      "推移的従属がない",
    ],
    answerIndex: 1,
    hints: [
      "atomic (原子的) という言葉が使われます。",
      "1 つのセルに 'tags=ruby,rails,sql' のような複数値を入れると違反。",
      "RDB の基本前提に近い条件。",
    ],
    explanation: {
      summary:
        "1NF: すべての属性が atomic (分解不可能な単一値)。1 セル 1 値、繰り返し列 (tag1, tag2, tag3) 禁止。",
      reason:
        "違反例: `tags VARCHAR` に 'ruby,rails,sql' とカンマ区切りで入れる。検索 (`WHERE tags LIKE '%rails%'`) は INDEX が効かず、追加 / 削除 / 集計も難しい。解消は別テーブル (post_tags) に切り出して 1:N か N:N に。",
      codeExample:
        "-- ❌ 1NF 違反 (繰り返しの値を 1 セルに)\nCREATE TABLE posts (\n  id BIGINT PRIMARY KEY,\n  title TEXT,\n  tags TEXT     -- 'ruby,rails,sql'\n);\n\n-- ✅ 1NF (タグを別テーブルに)\nCREATE TABLE posts (\n  id BIGINT PRIMARY KEY,\n  title TEXT\n);\nCREATE TABLE tags (\n  id BIGINT PRIMARY KEY,\n  name TEXT UNIQUE\n);\nCREATE TABLE post_tags (\n  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,\n  tag_id  BIGINT REFERENCES tags(id),\n  PRIMARY KEY (post_id, tag_id)\n);",
    },
  },
  {
    id: "db-002",
    categoryId: "db-design",
    difficulty: "beginner",
    type: "choice",
    question: "第 3 正規形 (3NF) の主な狙いは？",
    choices: [
      "全列を NOT NULL にする",
      "外部キーを全て削除する",
      "1 つの列に複数値を入れる",
      "非キー属性が他の非キー属性に従属しない (推移的従属の排除)",
    ],
    answerIndex: 3,
    hints: [
      "推移的従属 (transitive dependency) の排除がキーワード。",
      "PK → 非キー → 別の非キー という連鎖をなくす。",
      "繰り返しデータと更新異常を避ける目的。",
    ],
    explanation: {
      summary:
        "3NF: 非キー属性は『PK にだけ』直接依存する。`employee → department_id → department_name` のような推移は分離して department テーブルに。",
      reason:
        "正規化の主目的は『更新異常 (update anomaly) 防止』。department_name を employees テーブルに持つと、部署名変更で複数行 UPDATE が必要 (+ 不整合のリスク)。department を別テーブルにすれば 1 行更新で済む。実務では 3NF 〜 BCNF を目指しつつ、性能のために意図的に非正規化する場面もある。",
      codeExample:
        "-- ❌ 3NF 違反 (推移的従属)\nCREATE TABLE employees (\n  id BIGINT PRIMARY KEY,\n  name TEXT,\n  department_id BIGINT,\n  department_name TEXT,    -- ← department_id に従属\n  department_floor INT     -- ← 同じく\n);\n-- → 部署名変更で全社員行を UPDATE 必要、不整合の温床\n\n-- ✅ 3NF (分離)\nCREATE TABLE departments (\n  id BIGINT PRIMARY KEY,\n  name TEXT NOT NULL,\n  floor INT\n);\nCREATE TABLE employees (\n  id BIGINT PRIMARY KEY,\n  name TEXT,\n  department_id BIGINT REFERENCES departments(id)\n);",
    },
  },
  {
    id: "db-003",
    categoryId: "db-design",
    difficulty: "beginner",
    type: "choice",
    question:
      "Rails / 多くの SaaS で主キーに使われる『代理キー (surrogate key)』として現代の推奨は？",
    choices: [
      "BIGINT 連番 (デフォルト) または UUID v7 (分散・URL 公開用)",
      "メールアドレス (natural key)",
      "(name, created_at) の複合キー",
      "MD5 ハッシュ",
    ],
    answerIndex: 0,
    hints: [
      "Rails のデフォルトは BIGINT 連番。",
      "UUID v4 はランダムで INDEX が劣化、v7 は時系列順で性能良。",
      "メールや名前など『業務上の値』を PK にしない (変わりうる)。",
    ],
    explanation: {
      summary:
        "代理キー = 業務的意味のない『単なる識別子』。Rails 6+ デフォルトは BIGINT、ULID / UUID v7 (時系列順) も外部公開 / 分散環境で人気。",
      reason:
        "Natural key (email, 商品コードなど) は変更可能性 + 漏洩リスク。Surrogate key を PK にし、業務的に一意な値は UNIQUE 制約付きの別カラムに。UUID v4 はランダムなので B-Tree インデックスのページ分割が頻発し書き込み性能が劣化、v7 は時系列順なので順次挿入で高速。",
      codeExample:
        "-- ❌ Natural key (email 変更で全 FK 連鎖)\nCREATE TABLE users (\n  email TEXT PRIMARY KEY,\n  ...\n);\n\n-- ✅ Surrogate key + UNIQUE\nCREATE TABLE users (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,\n  email TEXT UNIQUE NOT NULL,\n  ...\n);\n\n-- UUID v7 (URL 公開・分散 ID 生成)\n-- Rails 7.1+ では generates_token_for や ULID gem も選択肢\nCREATE TABLE posts (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),\n  ...\n);",
    },
  },
  {
    id: "db-004",
    categoryId: "db-design",
    difficulty: "beginner",
    type: "choice",
    question:
      "外部キー (FOREIGN KEY) を貼ることの最大のメリットは？",
    choices: [
      "DB レベルで参照整合性が保証される (orphan レコード防止)",
      "クエリが速くなる",
      "ディスク使用量が減る",
      "アプリ側で何もしなくて良くなる",
    ],
    answerIndex: 0,
    hints: [
      "アプリ側のバグや並行更新でも整合性を守る。",
      "ORM の検証だけでは不十分 (race condition で抜ける)。",
      "DELETE / UPDATE 時の挙動を ON DELETE / ON UPDATE で制御。",
    ],
    explanation: {
      summary:
        "FOREIGN KEY は『参照先が存在することを DB が保証』。アプリ層バグや race condition の防壁。Rails では migration で `foreign_key: true` を明示。",
      reason:
        "ON DELETE 句で挙動を選べる: **CASCADE** (連鎖削除)、**SET NULL** (FK を NULL に)、**RESTRICT / NO ACTION** (削除を拒否)。Rails の `dependent: :destroy` はアプリ層、DB の ON DELETE は DB 層 — 両方理解する。インデックスは自動で貼られないので、FK には別途 INDEX を貼るのが定番 (JOIN / 参照削除で使われる)。",
      codeExample:
        "-- 参照整合性 + INDEX\nCREATE TABLE posts (\n  id BIGINT PRIMARY KEY,\n  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  title TEXT\n);\nCREATE INDEX idx_posts_user_id ON posts(user_id);   -- FK には INDEX を別途\n\n-- Rails migration\nadd_reference :posts, :user, null: false, foreign_key: true, index: true\n# → users.id への FK + posts.user_id への INDEX が同時に",
    },
  },
  {
    id: "db-005",
    categoryId: "db-design",
    difficulty: "beginner",
    type: "text",
    question:
      "テーブル名・カラム名の命名で『複数形 vs 単数形』『snake_case vs camelCase』の Rails / 多くの SaaS の慣習は？(英語、複合語で 1〜2 単語)",
    answers: [
      "plural snake_case",
      "plural and snake_case",
      "snake_case plural",
      "snake_case",
      "plural",
    ],
    hints: [
      "テーブル名は users / posts / order_items のように複数形。",
      "カラム名は created_at / user_id のように小文字+アンダースコア。",
      "PascalCase / camelCase は『アプリ層』、DB は snake_case が一般的。",
    ],
    explanation: {
      summary:
        "テーブル名は複数形 (`users`, `order_items`)、識別子は snake_case (`user_id`, `created_at`)。Rails の規約 + 多くの SaaS / OSS の慣習。",
      reason:
        "Rails: テーブル `users` → モデル `User` の規約 (ActiveSupport::Inflector が複数化)。snake_case は SQL が大文字小文字を区別しないことが多く、quote なしで書けて読みやすい。例外: 中間テーブルは アルファベット順の単純連結 (`articles_users` 等)、結合エンティティが意味を持つなら個別名 (`memberships` 等)。",
      codeExample:
        "-- ✅ 推奨\nusers, posts, order_items, post_tags\nuser_id, created_at, published_at\n\n-- ❌ よくある混乱\nUser            -- 大文字単数 (Rails では Class 名と紛らわしい)\nUsers           -- PascalCase 複数 (一貫しない)\nuserId          -- camelCase (DB ではほぼ非標準)\nuserName        -- 同上\n\n-- 結合テーブル\npost_tags                -- 単純な N:N 結合\nmemberships              -- 結合自体が意味を持つ (joined_at など)\nteam_user_assignments    -- より明確に意図を表現",
    },
  },
  {
    id: "db-006",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "users と posts の 1:N リレーションの DB 設計として正しいのは？",
    choices: [
      "中間テーブル user_posts を作る",
      "JSON で全部 users に詰める",
      "posts テーブルに user_id (FK) を持たせる",
      "users テーブルに post_ids 配列カラムを持たせる",
    ],
    answerIndex: 2,
    hints: [
      "FK は『N 側』に持たせるのが基本。",
      "配列カラムや JSON は集計・参照整合性が弱い。",
      "中間テーブルは N:N で使う。",
    ],
    explanation: {
      summary:
        "1:N は『N 側に FK』。users 1 ← N posts なら `posts.user_id REFERENCES users(id)`。中間テーブルは N:N の時だけ。",
      reason:
        "もし users.post_ids INT[] にすると、(1) ある post の著者を逆引きしにくい、(2) FK 制約が貼れない、(3) 参照削除が複雑。RDB は『リレーション = 別テーブル + FK』が基本。`belongs_to :user` を持つ側が FK を持つ — Rails の規約も同じ。",
      codeExample:
        "-- ✅ 1:N\nCREATE TABLE users (id BIGINT PRIMARY KEY, name TEXT);\nCREATE TABLE posts (\n  id BIGINT PRIMARY KEY,\n  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  title TEXT\n);\nCREATE INDEX idx_posts_user_id ON posts(user_id);\n\n-- Rails\nclass User < ApplicationRecord\n  has_many :posts, dependent: :destroy\nend\nclass Post < ApplicationRecord\n  belongs_to :user   -- FK は posts.user_id\nend",
    },
  },
  {
    id: "db-007",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "posts と tags の N:N リレーション (1 投稿に複数タグ、1 タグに複数投稿) の DB 設計は？",
    choices: [
      "posts.tag_ids 配列カラム",
      "tags.post_ids 配列カラム",
      "両方の id をカンマ区切りで保存",
      "中間テーブル post_tags を作り、両者への FK を持つ (複合 PK or 別途 id + UNIQUE)",
    ],
    answerIndex: 3,
    hints: [
      "N:N は中間テーブル (join table / junction table) で表現。",
      "(post_id, tag_id) の複合 PK か、id + UNIQUE 制約。",
      "Rails の has_and_belongs_to_many or has_many :through に対応。",
    ],
    explanation: {
      summary:
        "N:N は中間テーブル必須。`post_tags(post_id, tag_id)` の複合 PK で『同じ組み合わせ重複』を防ぐ。意味のある属性 (assigned_at 等) を持たせるなら別途 id + UNIQUE。",
      reason:
        "中間テーブルが『独立したエンティティ』に育つことは多い (memberships が role / joined_at を持つなど)。最初から `has_many :through` (Rails) で組むと拡張に強い。中間テーブルにも created_at / updated_at を付けると履歴を追える。",
      codeExample:
        "-- ✅ シンプルな N:N\nCREATE TABLE post_tags (\n  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,\n  tag_id  BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,\n  PRIMARY KEY (post_id, tag_id)\n);\nCREATE INDEX idx_post_tags_tag_id ON post_tags(tag_id);  -- 逆引き用\n\n-- ✅ 属性を持つ中間 (推奨、拡張に強い)\nCREATE TABLE memberships (\n  id BIGINT PRIMARY KEY,\n  team_id BIGINT REFERENCES teams(id),\n  user_id BIGINT REFERENCES users(id),\n  role TEXT NOT NULL,\n  joined_at TIMESTAMPTZ,\n  UNIQUE (team_id, user_id)\n);\n\n-- Rails\nclass Post < ApplicationRecord\n  has_many :post_tags\n  has_many :tags, through: :post_tags\nend",
    },
  },
  {
    id: "db-008",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "次のうち、ポリモーフィック関連 (polymorphic association) が向くケースは？",
    choices: [
      "INDEX の代替",
      "コメントを Post / Photo / Video 等『多種類の親』に付けたい時 (commentable_type + commentable_id)",
      "users と posts のような単純な 1:N",
      "数値の集計用テーブル",
    ],
    answerIndex: 1,
    hints: [
      "親の型が複数候補ある時に使う。",
      "Rails の belongs_to :commentable, polymorphic: true。",
      "FK 制約は貼れないので、参照整合性は弱くなる。",
    ],
    explanation: {
      summary:
        "ポリモーフィック関連: `commentable_type` (型名) + `commentable_id` (FK 相当) で 1 つの comments テーブルが複数の親テーブルに紐づく。柔軟だが FK 制約が貼れないトレードオフ。",
      reason:
        "代替案: (1) 各親に専用テーブル (post_comments / photo_comments)、(2) STI (Single Table Inheritance) で commentable を 1 つの大テーブルに、(3) GraphQL の Union 風に多態を別の方法で。FK が無い → 孤児レコードが発生しやすい → アプリ層 + 定期チェックで補完。本当に必要か検討してから使う。",
      codeExample:
        "-- ポリモーフィック\nCREATE TABLE comments (\n  id BIGINT PRIMARY KEY,\n  commentable_type TEXT NOT NULL,    -- 'Post', 'Photo', 'Video'\n  commentable_id   BIGINT NOT NULL,\n  body TEXT,\n  created_at TIMESTAMPTZ\n);\nCREATE INDEX idx_comments_commentable\n  ON comments(commentable_type, commentable_id);\n\n-- Rails\nclass Comment < ApplicationRecord\n  belongs_to :commentable, polymorphic: true\nend\nclass Post < ApplicationRecord\n  has_many :comments, as: :commentable\nend\n\n-- ⚠️ FK が貼れない → 整合性チェッカーを別途\n-- SELECT * FROM comments WHERE commentable_type='Post'\n--   AND commentable_id NOT IN (SELECT id FROM posts);",
    },
  },
  {
    id: "db-009",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "DB 設計の時点で INDEX を貼るべきカラムは？",
    choices: [
      "PK だけ",
      "TEXT 型の列だけ",
      "WHERE / JOIN / ORDER BY で頻繁に使う列、特に外部キー (user_id 等) と UNIQUE 制約用の列",
      "全カラム",
    ],
    answerIndex: 2,
    hints: [
      "INDEX は SELECT を速くするが INSERT/UPDATE を遅くする (要バランス)。",
      "外部キーには PostgreSQL は自動で INDEX を貼らない (MySQL は貼る)。",
      "UNIQUE 制約は内部的に UNIQUE INDEX を作る。",
    ],
    explanation: {
      summary:
        "WHERE / JOIN / ORDER BY で使う列、特に外部キーには INDEX を意識して貼る。PG は FK に自動で INDEX を作らないので明示が必要。",
      reason:
        "Rails の `add_reference :posts, :user, foreign_key: true, index: true` がデフォルトで INDEX を作る理由。`null: false` も忘れずに (NOT NULL FK の方が JOIN の挙動が分かりやすい)。複合 INDEX は『等値 → 範囲 → ORDER BY』の順で組む (SQL ガイド 7 章)。INDEX を貼りすぎると INSERT / UPDATE が重くなる + ディスク使用量増。",
      codeExample:
        "-- 設計時に INDEX を意識\nCREATE TABLE posts (\n  id BIGINT PRIMARY KEY,\n  user_id BIGINT NOT NULL REFERENCES users(id),\n  status TEXT NOT NULL,\n  published_at TIMESTAMPTZ,\n  slug TEXT NOT NULL\n);\nCREATE INDEX idx_posts_user_id ON posts(user_id);             -- FK\nCREATE UNIQUE INDEX idx_posts_slug ON posts(slug);             -- URL 用\nCREATE INDEX idx_posts_status_published_at\n  ON posts(status, published_at DESC);                          -- 一覧クエリ用 (複合)\n\n-- Rails migration\nadd_reference :posts, :user, null: false, foreign_key: true, index: true\nadd_index :posts, :slug, unique: true\nadd_index :posts, [:status, :published_at], order: { published_at: :desc }",
    },
  },
  {
    id: "db-010",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "Rails の標準的なタイムスタンプカラム (`timestamps` で追加されるもの) は？",
    choices: [
      "insertedAt と modifiedAt",
      "ctime と mtime",
      "created_at と updated_at",
      "ts_created と ts_updated",
    ],
    answerIndex: 2,
    hints: [
      "Rails / 多くの OSS の規約。",
      "INSERT 時に created_at、UPDATE 毎に updated_at を自動更新。",
      "timestamps: null: false にして NOT NULL に。",
    ],
    explanation: {
      summary:
        "Rails の `t.timestamps` は `created_at` + `updated_at` を追加 (DEFAULT NOW / 自動更新)。デバッグ・並び替え・キャッシュキー・楽観ロック (Optimistic Locking) で必須。",
      reason:
        "Active Record が UPDATE 時に updated_at を自動セットするので、これに依存する仕組み (`cache_key`, `touch:`) が動く。published_at / deleted_at など別の意味のタイムスタンプは別カラムで明示。TIMESTAMPTZ (UTC + タイムゾーン情報) を使うのが推奨 (TIMESTAMP は TZ なし)。",
      codeExample:
        "-- Rails migration\nclass CreatePosts < ActiveRecord::Migration[7.1]\n  def change\n    create_table :posts do |t|\n      t.string :title, null: false\n      t.references :user, null: false, foreign_key: true\n      t.timestamps                          -- created_at, updated_at\n    end\n  end\nend\n\n-- 直接 SQL\nCREATE TABLE posts (\n  id BIGINT PRIMARY KEY,\n  ...\n  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 関連カラム (別の意味で必要なら別カラム)\npublished_at TIMESTAMPTZ          -- 公開日 (NULL = 下書き)\ndeleted_at   TIMESTAMPTZ          -- ソフト削除日 (NULL = 削除されてない)\nlast_seen_at TIMESTAMPTZ          -- 最終ログイン",
    },
  },
  {
    id: "db-011",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "『ソフト削除 (soft delete)』を実装する一般的な方法は？",
    choices: [
      "is_active を反転する",
      "deleted_at TIMESTAMPTZ を追加し、NULL なら有効、値があれば削除済み",
      "別 DB に移動する",
      "実際にレコードを削除する",
    ],
    answerIndex: 1,
    hints: [
      "物理削除しない代わりに deleted_at を埋める。",
      "WHERE deleted_at IS NULL がデフォルトスコープに。",
      "監査・復元・誤削除対策で頻出。",
    ],
    explanation: {
      summary:
        "`deleted_at TIMESTAMPTZ NULL` を追加し、削除時に NOW() をセット。検索時は `WHERE deleted_at IS NULL` で生存レコードのみ。",
      reason:
        "メリット: 誤削除復元、監査、関連レコードを残せる。デメリット: 物理 INDEX サイズが減らない、UNIQUE 制約と相性悪 (`email UNIQUE` で『削除済み + 同 email の新規』が衝突)。対策: `UNIQUE (email) WHERE deleted_at IS NULL` (PG の partial index)。`paranoia` / `discard` gem (Rails) で透過的に。",
      codeExample:
        "-- スキーマ\nALTER TABLE users ADD COLUMN deleted_at TIMESTAMPTZ;\n\n-- 削除 / 復元\nUPDATE users SET deleted_at = NOW() WHERE id = 1;\nUPDATE users SET deleted_at = NULL  WHERE id = 1;\n\n-- 部分 INDEX で UNIQUE 制約を維持 (PostgreSQL)\nCREATE UNIQUE INDEX idx_users_email_active\n  ON users(email) WHERE deleted_at IS NULL;\n\n-- Rails (discard gem 推奨)\nclass User < ApplicationRecord\n  include Discard::Model        # default_scope { kept } を提供\nend\nUser.discard(id)                # deleted_at = NOW()\nUser.undiscard(id)              # NULL に戻す\nUser.kept                       # default_scope (deleted_at IS NULL)\nUser.discarded                  # 削除済みのみ\nUser.with_discarded             # 全件",
    },
  },
  {
    id: "db-012",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "本番 DB の大規模テーブルに『NOT NULL カラムを追加』する Zero Downtime Deployment (ZDD) の正しい手順は？",
    choices: [
      "1) NULL 許可で追加 → 2) アプリで全行に値を backfill → 3) NOT NULL 制約を追加 (場合により別 migration)",
      "ALTER TABLE で一気に NOT NULL カラム追加",
      "テーブルを drop して再作成",
      "ダウンタイムを取って全部やり直す",
    ],
    answerIndex: 0,
    hints: [
      "大規模テーブルへの NOT NULL 追加は table lock 時間が長い。",
      "段階的に: NULL 許可 → backfill → NOT NULL 制約。",
      "Strong Migrations gem (Rails) がアンチパターンを警告。",
    ],
    explanation: {
      summary:
        "ZDD の鉄則: 大規模テーブルの DDL は『1 migration で一気に』ではなく、(1) NULL 許可で追加 (短時間) → (2) backfill (アプリ稼働中に小分け) → (3) NOT NULL 制約。場合により default 値も同様に分ける。",
      reason:
        "PostgreSQL は ALTER TABLE が ACCESS EXCLUSIVE ロックを取る — 巨大テーブルだと数十分ロックでサービス停止。`ADD COLUMN NOT NULL DEFAULT 'x'` は 11+ で改善されたがリスクあり。段階的アプローチで安全。`strong_migrations` gem (Rails) が危険な migration を検出してアドバイス。Active Record 7+ は `disable_ddl_transaction!` + `CONCURRENTLY` index も簡単に。",
      codeExample:
        "-- Step 1: NULL 許可で追加 (短時間)\nALTER TABLE users ADD COLUMN role TEXT;\n\n-- Step 2: 既存行を backfill (アプリ稼働中、batch で)\nUPDATE users SET role = 'member' WHERE role IS NULL AND id BETWEEN 1 AND 10000;\n-- 繰り返し...\n\n-- Step 3: NOT NULL 制約 (短時間、全行に値があれば即時)\nALTER TABLE users ALTER COLUMN role SET NOT NULL;\n\n-- Rails (strong_migrations gem)\nclass AddRoleToUsers < ActiveRecord::Migration[7.1]\n  def up\n    safety_assured { add_column :users, :role, :string }\n  end\n  # backfill は別 migration or rake task で\nend\n\n-- INDEX も巨大テーブルでは CONCURRENTLY\nclass AddIndexConcurrent < ActiveRecord::Migration[7.1]\n  disable_ddl_transaction!\n  def change\n    add_index :posts, :slug, algorithm: :concurrently\n  end\nend",
    },
  },
  {
    id: "db-013",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "金額・通貨の DB 型として推奨されるのは？",
    choices: [
      "FLOAT / DOUBLE (浮動小数点)",
      "TEXT で文字列保存",
      "INT (円なら問題なし)",
      "DECIMAL(precision, scale) / NUMERIC (精度を保証)",
    ],
    answerIndex: 3,
    hints: [
      "金額は誤差が出てはいけない。",
      "FLOAT は 2 進数浮動小数 → 0.1 + 0.2 ≠ 0.3 の罠。",
      "DECIMAL は固定精度 (任意桁数の十進数を正確に保持)。",
    ],
    explanation: {
      summary:
        "金額・通貨は `DECIMAL(precision, scale)` (PG: NUMERIC) で固定精度。FLOAT は浮動小数の誤差で 1 円ずれる事故が起きる。",
      reason:
        "Rails では `t.decimal :amount, precision: 10, scale: 2`。または整数で『最小単位』(円ならそのまま、ドルなら cents) を保存 + 表示時に変換する流派もある (money-rails gem)。通貨混在 (USD / EUR / JPY) の DB は別カラム currency も必須。マイクロ単位の課金 / 利息計算は scale を多めに。",
      codeExample:
        "-- ✅ 推奨\nCREATE TABLE orders (\n  id BIGINT PRIMARY KEY,\n  amount_cents BIGINT NOT NULL,           -- 整数 (最小単位)\n  currency CHAR(3) NOT NULL,              -- 'USD', 'JPY', 'EUR'\n  -- または\n  amount DECIMAL(15, 2) NOT NULL,         -- 固定精度\n  ...\n);\n\n-- ❌ FLOAT (誤差の温床)\nCREATE TABLE orders (\n  amount FLOAT  -- 0.1 + 0.2 = 0.30000000000000004\n);\n\n-- Rails\nt.decimal :amount, precision: 10, scale: 2, null: false\n-- または money-rails\nt.monetize :amount\n# → amount_cents (integer) + amount_currency (string) を自動生成",
    },
  },
  {
    id: "db-014",
    categoryId: "db-design",
    difficulty: "intermediate",
    type: "choice",
    question:
      "DB の文字列列で『可変長で長さ制限なし』に向くデータ型は？",
    choices: [
      "VARCHAR(255) 一択",
      "BLOB",
      "TEXT (PostgreSQL は VARCHAR と同性能、長さ制限が不要なら TEXT 推奨)",
      "CHAR(255)",
    ],
    answerIndex: 2,
    hints: [
      "PostgreSQL: TEXT と VARCHAR は内部実装ほぼ同じで性能差なし。",
      "MySQL: VARCHAR(N) で N を指定するか、TEXT (大きなテキスト用)。",
      "長さ制限が必要なら CHECK や VARCHAR(N)。",
    ],
    explanation: {
      summary:
        "PostgreSQL では TEXT と VARCHAR(N) の性能差は無く、長さ制限が業務要件にあるなら CHECK 制約か VARCHAR(N) を、無いなら TEXT が推奨。MySQL は VARCHAR(N) と TEXT で挙動が違う (TEXT は大きなテキスト向け、index 制限あり)。",
      reason:
        "歴史的に VARCHAR の長さ制限は『DB のため』だったが、現代の PG では意味が薄い。アプリ層 (Rails の validates length:) でビジネスロジック側のバリデーションをし、DB は緩めに。CHAR(N) は固定長 (空白パディングがされる) — 通常使わない。BLOB / BYTEA はバイナリ (画像 / ファイル) 用、テキストには使わない。",
      codeExample:
        "-- PostgreSQL\ntitle      TEXT NOT NULL,              -- 自由テキスト (推奨)\nslug       VARCHAR(255) NOT NULL,      -- 業務要件で 255 まで\ncode       CHAR(8),                    -- 固定長 (滅多に使わない)\nemail      TEXT,                       -- アプリ側で長さ + 形式検証\n\n-- MySQL\ntitle      VARCHAR(255) NOT NULL,      -- index に乗せやすい\nbody       TEXT,                       -- 大きなテキスト (index 制限あり)\nbody       LONGTEXT,                   -- 4GB まで\n\n-- Rails\nt.string :title, null: false                    -- VARCHAR(255) 相当\nt.text   :body                                  -- TEXT 相当\nvalidates :title, length: { maximum: 120 }     -- アプリ層で",
    },
  },
  {
    id: "db-015",
    categoryId: "db-design",
    difficulty: "advanced",
    type: "choice",
    question:
      "次の DB 設計アンチパターンとして有名な『EAV モデル』とは？",
    choices: [
      "Event-Action-Validation の略",
      "Entity-Attribute-Value: 列を増やさず (entity_id, attribute, value) の縦持ちで全属性を保存する設計",
      "拡張可能な FK 設計",
      "外部 API 連携用の中間モデル",
    ],
    answerIndex: 1,
    hints: [
      "可変な属性を扱うために『縦持ち』で全部 1 テーブルに入れる手法。",
      "柔軟だが集計・型保証・JOIN が悪夢に。",
      "JSONB やスキーマ拡張で代替するのが現代。",
    ],
    explanation: {
      summary:
        "EAV (Entity-Attribute-Value): `product_properties(product_id, key, value)` のように属性を縦持ちする設計。スキーマ変更なしで属性追加できるが、型保証なし / JOIN 連鎖 / 集計困難。現代は JSONB / スキーマ拡張で代替。",
      reason:
        "実装が EAV になりがちなケース: 商品カテゴリごとに違う属性 (服: サイズ / 色、本: 著者 / ISBN)、ユーザー定義属性、設定値。PostgreSQL なら JSONB + GIN index、もしくはサブタイプ毎にテーブル分離 (Books / Clothes) の方が安全。EAV はやむを得ない時に限定。",
      codeExample:
        "-- ❌ EAV (避ける)\nCREATE TABLE product_properties (\n  id BIGINT PRIMARY KEY,\n  product_id BIGINT REFERENCES products(id),\n  key TEXT,                              -- 'size', 'color', 'author'\n  value TEXT                              -- '42', 'red', 'Alice'\n);\n-- 検索: `WHERE key='size' AND value='42'` の JOIN 地獄\n-- 型なし、サイズが '42' (string) vs 42 (int) で不整合\n\n-- ✅ 代替 1: JSONB (PostgreSQL)\nCREATE TABLE products (\n  id BIGINT PRIMARY KEY,\n  name TEXT,\n  attributes JSONB NOT NULL DEFAULT '{}'::jsonb\n);\nCREATE INDEX idx_products_attrs ON products USING GIN (attributes);\n-- 検索: WHERE attributes @> '{\"size\":\"M\"}'\n\n-- ✅ 代替 2: サブタイプ毎にテーブル\nCREATE TABLE clothes (\n  id BIGINT PRIMARY KEY,\n  product_id BIGINT REFERENCES products(id),\n  size TEXT,\n  color TEXT\n);\nCREATE TABLE books (\n  id BIGINT PRIMARY KEY,\n  product_id BIGINT REFERENCES products(id),\n  isbn TEXT UNIQUE,\n  author TEXT\n);",
    },
  },
  {
    id: "db-016",
    categoryId: "db-design",
    difficulty: "advanced",
    type: "choice",
    question:
      "Rails で履歴 (誰がいつ何を変えたか) を残す代表的な gem は？",
    choices: [
      "paper_trail / audited",
      "history-tracker",
      "version-stack",
      "deep-log",
    ],
    answerIndex: 0,
    hints: [
      "model に has_paper_trail / audited を付ける。",
      "versions / audits テーブルに変更履歴を JSON で保存。",
      "ロールバック・diff 表示・コンプライアンスで頻出。",
    ],
    explanation: {
      summary:
        "`paper_trail` / `audited` は Rails で標準的な audit log gem。変更前後の値を JSON で別テーブルに保存し、調査 / ロールバック / 監査対応で使う。",
      reason:
        "GDPR / SOX / SOC2 などの規制対応で必須。paper_trail は versions テーブルに object / object_changes を保存。audited は audits テーブルに audited_changes (JSON)。両方とも『誰が』(whodunnit / user_id) を after_action 等でセット。書き込みコスト + ストレージが増えるので、対象モデルを絞り込む。",
      codeExample:
        "# Gemfile\ngem 'paper_trail'\n\n# rails g paper_trail:install → versions テーブル作成\n\n# Model\nclass Post < ApplicationRecord\n  has_paper_trail                              # 全 attr を追跡\n  # has_paper_trail only: [:title, :body]      # 一部だけ\n  # has_paper_trail ignore: [:updated_at]\nend\n\n# 使う\npost = Post.find(1)\npost.versions                                  # 履歴の配列\npost.versions.last.reify                       # 1 つ前のオブジェクト復元\npost.versions.last.object_changes              # JSON 差分\npost.versions.where('created_at > ?', 1.week.ago)\n\n# whodunnit (誰が変更したか)\nclass ApplicationController < ActionController::Base\n  before_action :set_paper_trail_whodunnit\n  # → PaperTrail.request.whodunnit = current_user.id\nend\n\n# audited\nclass Post < ApplicationRecord\n  audited                                       # audits テーブルに記録\n  # audited only: [:title]\nend\nPost.last.audits\nPost.last.audits.last.audited_changes",
    },
  },
  {
    id: "db-017",
    categoryId: "db-design",
    difficulty: "advanced",
    type: "choice",
    question:
      "DB 設計で『non-deterministic な値』(乱数 / シーケンス) を主キーに使う場合の典型的な落とし穴は？",
    choices: [
      "UUID は遅すぎて使えない",
      "INDEX は不要になる",
      "PK にはならない",
      "UUID v4 はランダム順なので B-Tree INDEX のページ分割が頻発し、書き込み性能が劣化する (v7/ULID で時系列順に)",
    ],
    answerIndex: 3,
    hints: [
      "B-Tree は値順に並ぶ → 値がランダムだと挿入位置がバラバラ。",
      "ページ分割 = 既存ページの分割 + 新ページ作成で I/O 増。",
      "時系列順の UUID (v7 / ULID) が現代の解。",
    ],
    explanation: {
      summary:
        "UUID v4 (完全ランダム) を PK にすると B-Tree のページ分割で書き込みが遅くなる。UUID v7 / ULID (時系列順 + ランダム) を選ぶか、BIGINT 連番 + UUID 別カラムが定番。",
      reason:
        "B-Tree INDEX は値順に保持 → 連番ならページ末尾に追記で済むが、ランダム値だと中央のページに割り込む → ページ分割。これが連続すると VACUUM の負荷も増える。UUID v7 (RFC 9562, 2024 標準化) は先頭がタイムスタンプ + ランダムで時系列順を保つ。Rails 7.1+ は `generates_token_for` + UUID で URL 公開用トークンを安全に生成可能。",
      codeExample:
        "-- ❌ UUID v4 を PK (大量書き込みで性能劣化)\nCREATE TABLE posts (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),    -- v4\n  ...\n);\n\n-- ✅ UUID v7 (時系列順、PG 17+ / 拡張で)\nCREATE TABLE posts (\n  id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),\n  ...\n);\n\n-- ✅ ULID (時系列順、Crockford Base32)\n-- gem 'ulid' (Ruby) で生成\n\n-- ✅ 折衷案: BIGINT 連番 PK + UUID 別カラム\nCREATE TABLE posts (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,\n  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),\n  ...\n);\n-- 内部 JOIN は BIGINT、公開 URL は UUID",
    },
  },
  {
    id: "db-018",
    categoryId: "db-design",
    difficulty: "advanced",
    type: "choice",
    question:
      "テーブル設計で『公開フラグ』を表すとき、bool published と timestamp published_at どちらが良い？",
    choices: [
      "published_at TIMESTAMPTZ NULL — 『公開時刻』と『下書き (NULL)』を同時に表現できる",
      "published BOOLEAN — シンプルでわかりやすい",
      "両方持つ",
      "ステータス列挙の TEXT を持つ",
    ],
    answerIndex: 0,
    hints: [
      "BOOLEAN だと公開時刻が分からない。",
      "NULL を活用すると『未公開』を自然に表現できる。",
      "予約投稿 (将来時刻) もこれで表現可能。",
    ],
    explanation: {
      summary:
        "`published_at TIMESTAMPTZ NULL` で『公開時刻 + 下書き (NULL)』を 1 列で表現。BOOLEAN だと別途 published_at が必要になり情報が重複する。",
      reason:
        "応用: `published_at > NOW()` で予約投稿、`WHERE published_at IS NOT NULL AND published_at <= NOW()` で公開済みを抽出。同じパターン: `deleted_at` (ソフト削除)、`completed_at` (完了日)、`approved_at` (承認日)。ステータスが 3 つ以上 (draft / review / published / archived) なら status enum 列 (or 専用テーブル) の方が表現力がある。",
      codeExample:
        "-- ✅ 推奨\nCREATE TABLE posts (\n  id BIGINT PRIMARY KEY,\n  title TEXT,\n  body TEXT,\n  published_at TIMESTAMPTZ        -- NULL = 下書き、時刻あり = 公開\n);\nCREATE INDEX idx_posts_published_at ON posts(published_at DESC)\n  WHERE published_at IS NOT NULL;\n\n-- 公開済みを取得\nSELECT * FROM posts\nWHERE published_at IS NOT NULL\n  AND published_at <= NOW()\nORDER BY published_at DESC;\n\n-- 予約投稿 (将来時刻でセット)\nUPDATE posts SET published_at = '2026-12-01 10:00' WHERE id = 5;\n\n-- ステータスが 3+ ならステータス列\nstatus TEXT NOT NULL CHECK (status IN ('draft', 'review', 'published', 'archived'))\n-- または enum (PG)\nCREATE TYPE post_status AS ENUM ('draft', 'review', 'published', 'archived');\nstatus post_status NOT NULL DEFAULT 'draft'\n\n-- Rails では enum でラップ\nclass Post < ApplicationRecord\n  enum status: { draft: 0, review: 1, published: 2, archived: 3 }\nend",
    },
  },
];
